apiVersion: v1
kind: Service
metadata:
  name: backend-service # This name is how other pods (like frontend) can reach the backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 4000 
  type: ClusterIP 