apiVersion: v1
kind: Service
metadata:
  name: backend-service # This name is how other pods (like frontend) can reach the backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000 # Port the service will be exposed on WITHIN the cluster
      targetPort: 5000 # !!! Port on the POD to forward traffic to (must match containerPort above) !!!
  type: ClusterIP # Only reachable within the cluster network (default)