apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment # Name for this deployment object
spec:
  replicas: 1 # Number of pod instances to run
  selector:
    matchLabels:
      app: frontend # Selects pods with this label
  template: # Blueprint for the pods
    metadata:
      labels:
        app: frontend # Label applied to the pods
    spec:
      containers:
      - name: frontend-container # Name of the container within the pod
        image: your-frontend-image:latest # !!! REPLACE with your actual frontend image name and tag !!!
        imagePullPolicy: IfNotPresent # Important for local images
        ports:
        - containerPort: 3000 # !!! CHANGE if your frontend runs on a different port inside the container !!!