apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket
  template:
    metadata:
      labels:
        app: socket
    spec:
      containers:
      - name: socket-container
        image: my-socket-app:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4001 